/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherLoginRouteImport } from './routes/teacher-login'
import { Route as TcDownloadRouteImport } from './routes/tc-download'
import { Route as StudentLoginRouteImport } from './routes/student-login'
import { Route as MpdRouteImport } from './routes/mpd'
import { Route as MarksheetRouteImport } from './routes/marksheet'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EnquiryRouteImport } from './routes/enquiry'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUploadRouteImport } from './routes/_authenticated/admin/upload'
import { Route as AuthenticatedAdminTcRouteImport } from './routes/_authenticated/admin/tc'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin/students'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'

const TeacherLoginRoute = TeacherLoginRouteImport.update({
  id: '/teacher-login',
  path: '/teacher-login',
  getParentRoute: () => rootRouteImport,
} as any)
const TcDownloadRoute = TcDownloadRouteImport.update({
  id: '/tc-download',
  path: '/tc-download',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student-login',
  path: '/student-login',
  getParentRoute: () => rootRouteImport,
} as any)
const MpdRoute = MpdRouteImport.update({
  id: '/mpd',
  path: '/mpd',
  getParentRoute: () => rootRouteImport,
} as any)
const MarksheetRoute = MarksheetRouteImport.update({
  id: '/marksheet',
  path: '/marksheet',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiryRoute = EnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUploadRoute =
  AuthenticatedAdminUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTcRoute = AuthenticatedAdminTcRouteImport.update({
  id: '/tc',
  path: '/tc',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/enquiry': typeof EnquiryRoute
  '/gallery': typeof GalleryRoute
  '/marksheet': typeof MarksheetRoute
  '/mpd': typeof MpdRoute
  '/student-login': typeof StudentLoginRoute
  '/tc-download': typeof TcDownloadRoute
  '/teacher-login': typeof TeacherLoginRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/tc': typeof AuthenticatedAdminTcRoute
  '/admin/upload': typeof AuthenticatedAdminUploadRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/enquiry': typeof EnquiryRoute
  '/gallery': typeof GalleryRoute
  '/marksheet': typeof MarksheetRoute
  '/mpd': typeof MpdRoute
  '/student-login': typeof StudentLoginRoute
  '/tc-download': typeof TcDownloadRoute
  '/teacher-login': typeof TeacherLoginRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/tc': typeof AuthenticatedAdminTcRoute
  '/admin/upload': typeof AuthenticatedAdminUploadRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/enquiry': typeof EnquiryRoute
  '/gallery': typeof GalleryRoute
  '/marksheet': typeof MarksheetRoute
  '/mpd': typeof MpdRoute
  '/student-login': typeof StudentLoginRoute
  '/tc-download': typeof TcDownloadRoute
  '/teacher-login': typeof TeacherLoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/tc': typeof AuthenticatedAdminTcRoute
  '/_authenticated/admin/upload': typeof AuthenticatedAdminUploadRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/enquiry'
    | '/gallery'
    | '/marksheet'
    | '/mpd'
    | '/student-login'
    | '/tc-download'
    | '/teacher-login'
    | '/admin'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/tc'
    | '/admin/upload'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/enquiry'
    | '/gallery'
    | '/marksheet'
    | '/mpd'
    | '/student-login'
    | '/tc-download'
    | '/teacher-login'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/tc'
    | '/admin/upload'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/enquiry'
    | '/gallery'
    | '/marksheet'
    | '/mpd'
    | '/student-login'
    | '/tc-download'
    | '/teacher-login'
    | '/_authenticated/admin'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/tc'
    | '/_authenticated/admin/upload'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EnquiryRoute: typeof EnquiryRoute
  GalleryRoute: typeof GalleryRoute
  MarksheetRoute: typeof MarksheetRoute
  MpdRoute: typeof MpdRoute
  StudentLoginRoute: typeof StudentLoginRoute
  TcDownloadRoute: typeof TcDownloadRoute
  TeacherLoginRoute: typeof TeacherLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher-login': {
      id: '/teacher-login'
      path: '/teacher-login'
      fullPath: '/teacher-login'
      preLoaderRoute: typeof TeacherLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tc-download': {
      id: '/tc-download'
      path: '/tc-download'
      fullPath: '/tc-download'
      preLoaderRoute: typeof TcDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-login': {
      id: '/student-login'
      path: '/student-login'
      fullPath: '/student-login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mpd': {
      id: '/mpd'
      path: '/mpd'
      fullPath: '/mpd'
      preLoaderRoute: typeof MpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marksheet': {
      id: '/marksheet'
      path: '/marksheet'
      fullPath: '/marksheet'
      preLoaderRoute: typeof MarksheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry': {
      id: '/enquiry'
      path: '/enquiry'
      fullPath: '/enquiry'
      preLoaderRoute: typeof EnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/upload': {
      id: '/_authenticated/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AuthenticatedAdminUploadRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tc': {
      id: '/_authenticated/admin/tc'
      path: '/tc'
      fullPath: '/admin/tc'
      preLoaderRoute: typeof AuthenticatedAdminTcRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminTcRoute: typeof AuthenticatedAdminTcRoute
  AuthenticatedAdminUploadRoute: typeof AuthenticatedAdminUploadRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
    AuthenticatedAdminTcRoute: AuthenticatedAdminTcRoute,
    AuthenticatedAdminUploadRoute: AuthenticatedAdminUploadRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EnquiryRoute: EnquiryRoute,
  GalleryRoute: GalleryRoute,
  MarksheetRoute: MarksheetRoute,
  MpdRoute: MpdRoute,
  StudentLoginRoute: StudentLoginRoute,
  TcDownloadRoute: TcDownloadRoute,
  TeacherLoginRoute: TeacherLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
