/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MpdRouteImport } from './routes/mpd'
import { Route as MarksheetRouteImport } from './routes/marksheet'
import { Route as EnquiryRouteImport } from './routes/enquiry'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const MpdRoute = MpdRouteImport.update({
  id: '/mpd',
  path: '/mpd',
  getParentRoute: () => rootRouteImport,
} as any)
const MarksheetRoute = MarksheetRouteImport.update({
  id: '/marksheet',
  path: '/marksheet',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiryRoute = EnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/enquiry': typeof EnquiryRoute
  '/marksheet': typeof MarksheetRoute
  '/mpd': typeof MpdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/enquiry': typeof EnquiryRoute
  '/marksheet': typeof MarksheetRoute
  '/mpd': typeof MpdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/enquiry': typeof EnquiryRoute
  '/marksheet': typeof MarksheetRoute
  '/mpd': typeof MpdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contact' | '/enquiry' | '/marksheet' | '/mpd'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/enquiry' | '/marksheet' | '/mpd'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/enquiry'
    | '/marksheet'
    | '/mpd'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EnquiryRoute: typeof EnquiryRoute
  MarksheetRoute: typeof MarksheetRoute
  MpdRoute: typeof MpdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mpd': {
      id: '/mpd'
      path: '/mpd'
      fullPath: '/mpd'
      preLoaderRoute: typeof MpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marksheet': {
      id: '/marksheet'
      path: '/marksheet'
      fullPath: '/marksheet'
      preLoaderRoute: typeof MarksheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry': {
      id: '/enquiry'
      path: '/enquiry'
      fullPath: '/enquiry'
      preLoaderRoute: typeof EnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EnquiryRoute: EnquiryRoute,
  MarksheetRoute: MarksheetRoute,
  MpdRoute: MpdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
